### ISSUE TITLE
Creating weather report via the provided macros are seen by all

### ISSUE THREAD

**Issue by Klala** [ntriel/pf1-weather-macros#1]
I disabled all my other modules and that problem was still there but when I tested it on a test game it was working so I figured the problem is actually in the name. It appears that when the gamemaster's name is anything other than "Gamemaster" the message created by the macro will be shown to all. If the Gamemaster's name is "Gamemaster" then using the macro will send a whisper to the GM and the message will not be public.

A bit of an oversight perhaps?

**Comment by ntriel** [comment]
Ahh yes, I used ChatMessage.getWhisperRecipients("Gamemaster"), let me get that changed to dynamically get the name of the GM and push that update.

**Comment by ntriel** [comment]
Just pushed update that will now whisper to GMs regardless of name.
